#exemplo01 - StartCodon.pl
##!/usr/bin/perl

$sequencia = "AGCTAAATCGAATCCCGAAACTAAACGTCCCGTTTTGGTATACATTCATGACTCGGTGGTGTTTGTTATAGGGAAAATCATCGTGAATATTATGGACCTGATTATTTTATTAAAAAGGAATTCATGTTGTATTAATTACCATACAATATCGTTTGGGAGTTCTAGGTTTTTGAGCTTAAATTCTGAAGAGCTTAATGTACCCGGTAATGCTGGCCTTAAGGATCAAGTTATGGCGAATTCTTTACGTTGGATTAAAAATAATTGTGCCAATTTCGGTGGTAATCCTGATAACATCACTGTCTTTGGTGAGAGTGCTGGTGGAGCCTCTGCCCATTACATGATGTTAACTGAACAAACACGTGGTCTCTTCCATCGTGGATTTTAATGTCTGGCAATGCTGTATGTCCTTGGCCATTAGTCAAAATCAACATCGTGCTTATGCTATAGCTAAATTGACTGGGTATAGAATTCAGGGTGAAAATAATGATAAGGA";


# A enzima EcoRI reconhece o sítio GAATTC

$ecor1 = "GAATTC";

$hinf1 = "GA[ACTG]TC";

if ( $sequencia =~ /$ecor1/ ) {
	print "A sequencia possui sitio da enzima EcoRI!\n";
}

#@resultado = ($sequencia =~ /$ecor1/g);

#print "@resultado";



if (@sitios = $sequencia =~ /$hinf1/g) {
  $num = @sitios;
  print "A sequência possui $num sítios hinf1:\n @sitios\n";
}

exit;
